import fs from "fs";
import path from "path";
import { resolveRailsAppRoot } from "./resolveRailsAppRoot";
import { analyzeSourceFile, type AnalyzedSource, type TestMember } from "./testAnalyzer";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: rails g test <source-file>");
  console.error("");
  console.error("Examples:");
  console.error("  rails g test app/controllers/admin/admin.controller.ts");
  console.error("  rails g test @services/auth/authLogin.service");
  console.error("  rails g test app/jobs/example.job.ts");
  process.exit(1);
}

const root = resolveRailsAppRoot();
const analyzed = analyzeSourceFile(root, args[0]);

if (fs.existsSync(analyzed.testPath)) {
  console.error(
    `\x1b[31m[Error]\x1b[0m Test file already exists: ${path.relative(root, analyzed.testPath)}`,
  );
  process.exit(1);
}

const content = renderTestFile(analyzed);
const dir = path.dirname(analyzed.testPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(analyzed.testPath, content);

console.log(`\x1b[32mCREATE\x1b[0m ${path.relative(root, analyzed.testPath)}`);
printSummary(root, analyzed);

function renderTestFile(a: AnalyzedSource): string {
  const header = `/**
 * Generated by ts-rails — fill in arrange / act / assert for each it.todo below.
 * Source: ${a.sourceRel}
 */`;

  const setup = setupBlock(a);

  const memberBlocks = a.members
    .map((m) => describeMember(a, m))
    .join("\n\n");

  const body =
    a.members.length > 0
      ? memberBlocks
      : `  it.todo("add tests for ${a.className}");`;

  return `${header}
${a.importStatement}

describe("${a.className}", () => {
${setup}${body}
});
`;
}

function setupBlock(a: AnalyzedSource): string {
  switch (a.kind) {
    case "controller":
      return `  // const controller = new ${a.className}();\n  // TODO: mock req, res, next (Express) before calling actions\n\n`;
    case "service":
      return `  // const subject = new ${a.className}();\n\n`;
    case "job":
      return `  // const job = new ${a.className}();\n\n`;
    case "mailer":
      return `  // Mailer uses static methods — no instance needed\n\n`;
    case "channel":
      return `  // TODO: mock Socket / Server from socket.io\n\n`;
    case "route":
      return `  // const route = new ${a.className}();\n\n`;
    default:
      return "";
  }
}

function describeMember(a: AnalyzedSource, member: TestMember): string {
  if (member.isStatic || a.kind === "mailer") {
    return `  describe("${member.name}", () => {
    it.todo("${member.name}");
  });`;
  }

  return `  describe("${member.name}", () => {
    it.todo("${member.name}");
  });`;
}

function printSummary(root: string, a: AnalyzedSource): void {
  const relTest = path.relative(root, a.testPath);
  const memberList =
    a.members.length > 0
      ? a.members.map((m) => m.name).join(", ")
      : "(none detected — add it.todo manually)";

  console.log(`
\x1b[33mSummary\x1b[0m
  Kind:    ${a.kind}
  Class:   ${a.className}
  Methods: ${memberList}
  Run:     \x1b[36mpnpm test ${relTest}\x1b[0m
`);
}
