import fs from "fs";
import path from "path";
import { resolveRailsAppRoot } from "./resolveRailsAppRoot";
import { pascalCase } from "./generatorHelpers";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:mailer Name [action action...]");
  process.exit(1);
}

const name = args[0];
const actions =
  args.slice(1).length > 0 ? args.slice(1) : ["notify"];
const mailerClass = `${pascalCase(name)}Mailer`;
const root = resolveRailsAppRoot();
const mailerPath = path.join(
  root,
  `app/mailers/${name.toLowerCase()}.mailer.ts`,
);
const viewSlug = `${name.toLowerCase()}.mailer`;

const actionBlocks = actions
  .map(
    (action) => `  static async ${action}(to: string, data: Record<string, unknown>) {
    await this.deliver({
      to,
      subject: "${action.replace(/_/g, " ")}",
      html: this.render("${viewSlug}/${action}", {
        ...data,
        appName: "Irwin Framework",
      }),
    });
  }`,
  )
  .join("\n\n");

const template = `import { ApplicationMailer } from "./application.mailer";

/**
 * ${mailerClass} - Generated by ts-rails
 */
export class ${mailerClass} extends ApplicationMailer {
${actionBlocks}
}
`;

const dir = path.dirname(mailerPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(mailerPath, template);

console.log(
  `\x1b[32mCREATE\x1b[0m app/mailers/${name.toLowerCase()}.mailer.ts`,
);
console.log(`
\x1b[33mUsage:\x1b[0m
import { ${mailerClass} } from "@mailers/${name.toLowerCase()}.mailer";

await ${mailerClass}.${actions[0]}("user@example.com", { name: "User" });

\x1b[33mNote:\x1b[0m Add Pug view at app/views/${viewSlug}/${actions[0]}.pug if you use this.render().
`);
