import fs from "fs";
import path from "path";
import { resolveRailsAppRoot } from "./resolveRailsAppRoot";
import { pascalCase } from "./generatorHelpers";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:channel Name");
  process.exit(1);
}

const rawName = args[0].replace(/[^a-zA-Z0-9]/g, "");
const fileBase = rawName.charAt(0).toLowerCase() + rawName.slice(1);
const channelClass = `${pascalCase(rawName)}Channel`;
const root = resolveRailsAppRoot();
const channelPath = path.join(root, "app/channels", `${fileBase}.channel.ts`);
const roomName = `${fileBase}_room`;
const eventName = `${fileBase}:message`;

const template = `import { ApplicationChannel } from "./application.channel";

/**
 * ${channelClass} - Socket.IO channel (generated by ts-rails)
 */
export class ${channelClass} extends ApplicationChannel {
  async subscribe() {
    if (!(await this.ensureAuthenticated())) return;

    this.join("${roomName}");
    this.socket.on("${eventName}", (data: unknown) => this.handleMessage(data));
  }

  private async handleMessage(data: unknown) {
    const user = await this.getCurrentUser();
    if (!user) return;

    this.broadcastTo("${roomName}", "${eventName}", {
      user: { id: user.id },
      data,
      timestamp: new Date().toISOString(),
    });
  }
}
`;

const dir = path.dirname(channelPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(channelPath, template);

console.log(`\x1b[32mCREATE\x1b[0m app/channels/${fileBase}.channel.ts`);
console.log(`
\x1b[33mNext steps:\x1b[0m
1. Export in \x1b[35mapp/channels/index.ts\x1b[0m:
   export * from "./${fileBase}.channel";
2. Channels are registered via RailsApplication.channelClasses in configs/application.ts
`);
