import fs from "fs";
import path from "path";
import { resolveRailsAppRoot } from "./resolveRailsAppRoot";
import {
  ensureNamespaceServiceFile,
  fileBaseFromRaw,
  parseNamespace,
  pascalCase,
  resolveServiceParent,
} from "./generatorHelpers";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:service Name or Namespace/name");
  process.exit(1);
}

const { parts, subDir, rawName } = parseNamespace(args[0]);
const serviceName = `${pascalCase(rawName)}Service`;
const fileBase = fileBaseFromRaw(rawName);
const root = resolveRailsAppRoot();
const serviceDir = path.join(root, "app/services", subDir);
const servicePath = path.join(serviceDir, `${fileBase}.service.ts`);

const serviceParent = resolveServiceParent(root, parts, subDir);

const writeFile = (filePath: string, content: string) => {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log(`\x1b[32mCREATE\x1b[0m ${path.relative(root, filePath)}`);
};

ensureNamespaceServiceFile(root, subDir, serviceParent, writeFile);

const template = `import { ${serviceParent.parentClass} } from "${serviceParent.parentImportPath}";

/**
 * ${serviceName} - Generated by ts-rails
 */
export class ${serviceName} extends ${serviceParent.parentClass} {
  async execute(params: Record<string, unknown>) {
    // TODO: Implement business logic
    return params;
  }
}
`;

writeFile(servicePath, template);

const importPath = subDir
  ? `@services/${subDir}/${fileBase}.service`
  : `@services/${fileBase}.service`;

console.log(`
\x1b[33mUsage:\x1b[0m
import { ${serviceName} } from "${importPath}";

const result = await new ${serviceName}().execute(this.req.body);
`);
