import fs from "fs";
import path from "path";
import { resolveRailsAppRoot } from "./resolveRailsAppRoot";
import { pascalCase } from "./generatorHelpers";

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error("Usage: yarn g:job Name");
  process.exit(1);
}

const name = args[0];
const root = resolveRailsAppRoot();
const jobName = `${pascalCase(name)}Job`;
const jobPath = path.join(root, "app/jobs", `${name.toLowerCase()}.job.ts`);

const template = `import { ApplicationJob } from "./application.job";

/**
 * ${jobName} - Generated by ts-rails
 * Đăng ký qua export trong app/jobs/index.ts (auto-discovery trong configs/initializers/jobs.ts).
 */
export class ${jobName} extends ApplicationJob {
  /** Cron expression (node-cron). Để undefined nếu không chạy theo lịch — chỉ gọi perform() / performLater(). */
  static cron: string | undefined = undefined;

  async perform(..._args: unknown[]): Promise<void> {
    // TODO: Implement background logic
    console.log("[${jobName}] perform at", new Date().toISOString());
  }
}
`;

const dir = path.dirname(jobPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(jobPath, template);

console.log(`\x1b[32mCREATE\x1b[0m app/jobs/${name.toLowerCase()}.job.ts`);
console.log(`
\x1b[33mUsage:\x1b[0m
import { ${jobName} } from "@jobs/${name.toLowerCase()}.job";

await new ${jobName}().performLater();
// Hoặc bật cron: static cron = "0 * * * *";
`);
